version: "3"
services:
  express-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=rick
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev
