version: "3"
services:
  express-app:
    build: .
    # ports:
    # - "4000:3100" config in nginx
    env_file:
      - ./.env
    depends_on:
      - mongo # confirm the process order

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rick
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - mongo-db:/data/db # prevent the data loose when down

  redis:
    image: redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3100:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-db:
