version: "3"
services:
  express-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start

  nginx:
    ports:
      - "80:80" # differet from docker-compose
